Update all project dependencies
novoda/drop-cap pull request #3
Opened 2019-05-11 10:47 UTC by Mecharyry

## Problem
It's been a little while since this project got any love 😭 

## Solution
Let's update the project dependencies to androidX and use the latest supported versions 💥

2019-05-12 18:36 UTC, mr-archano requested changes

2019-05-12 18:36 UTC, mr-archano commented on build.gradle
> -task wrapper(type: Wrapper) {
why has this been removed?

2019-05-12 18:36 UTC, mr-archano commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
Is it worth updating to 5.4.1 or you reckon that would be a problem?
Also: it seems like the wrapper update is not complete, I would have expected to see the wrapper jar in this diff as well as the executable scripts. Have you followed the steps in the [official documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper)?

2019-05-13 07:19 UTC, Mecharyry commented on build.gradle
> -task wrapper(type: Wrapper) {
It was conflicting with some default one.

2019-05-13 07:19 UTC, Mecharyry commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
TBH, ASide did most of the updating 😅 I'll take a look at the official docs and update it.

2019-05-13 09:19 UTC, mr-archano commented on build.gradle
> -task wrapper(type: Wrapper) {
yes, because the `wrapper` task is already there. That syntax is not valid anymore in Gradle 5.x, as you need to configure the task, not creating it:
```
wrapper {
    gradleVersion = '5.4.1'
    distributionType = Wrapper.DistributionType.ALL
}
```

2019-05-13 09:20 UTC, mr-archano commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
You could just update the task `wrapper` configuration as needed (see comment) and then run `./gradlew wrapper` (twice to ensure that all the changes have been applied).

2019-05-15 16:04 UTC, Mecharyry commented on build.gradle
> -task wrapper(type: Wrapper) {
Wrapper re-added here -> https://github.com/novoda/drop-cap/pull/3/files#diff-c197962302397baf3a4cc36463dce5eaR16

2019-05-15 16:05 UTC, Mecharyry commented on sample/src/main/res/values/drop-cap-strings.xml
> +  <!--Not a typo, this is dummy text-->
Lint complaining about typos 😂

2019-05-15 16:05 UTC, Mecharyry commented on sample/src/main/res/layout/activity_drop_cap.xml
> +      style="@style/DropCap.Button"
Lint complaining about the button style being missing.

2019-05-20 07:58 UTC, mr-archano approved these changes

2019-05-23 08:37 UTC, merged